# Generated by Django 2.0.3 on 2018-04-22 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_context', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birthday', models.DateTimeField()),
                ('sexial', models.CharField(max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='introduction',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intro.People'),
        ),
    ]
